AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Heartbeat Manager
  
  Aggregate Heartbeats from Prometheus 

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    MemorySize: 128

    LoggingConfig:
      # Allowed values: Text | JSON
      LogFormat: Text

Parameters:
  Debug:
    Type: String
    Description: Debug flag
    Default: "false"
  Environment: 
    Type: String
    Description: environment
    Default: "development"

Resources:
  HeartbeatFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: heartbeat-manager/
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - x86_64
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: BUFFERED
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DEBUG: !Ref Debug
          #SECRETARN: !Ref SecretConfig
          APP_ENVIRONMENT: !Ref Environment
      Tags: 
        cost-reporter-team: data-plane-infra
        cost-reporter-service: heartbeat
        environment: !Ref Environment

  #SecretConfig:
  #  Type: AWS::SecretsManager::Secret
  #  Properties: 
  #    Description: Configuration for okta-k8s-bridge lambda
  #    Name: !Sub 'okta-k8s-bridge-${Environment}' 
  #    SecretString: "{}"

Outputs:
  HeartbeatFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt HeartbeatFunction.Arn
  HeartbeatFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HeartbeatFunctionRole.Arn
  HeartbeatFunctionUrlEndpoint:
    Description: "Heartbeat Function URL Endpoint"
    Value:
      Fn::GetAtt: HeartbeatFunctionUrl.FunctionUrl
